DEV:
  ENV: DEV
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'my_database://user_name:password@127.0.0.1/schema'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_COMMIT_ON_TEARDOWN: False
  SECRET_KEY: 'secret_key'

TEST:
  ENV: TEST
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'my_database://user_name:password@127.0.0.1/schema'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_COMMIT_ON_TEARDOWN: False
  SECRET_KEY: 'secret_key'

PROD:
  ENV: PROD
  DEBUG: False
  SQLALCHEMY_DATABASE_URI: 'my_database://user_name:password@127.0.0.1/schema'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_COMMIT_ON_TEARDOWN: False
  SECRET_KEY: 'secret_key'
